apiVersion: v1
kind: Service
metadata:
  name: eco-predict-backend #service-name
  namespace: eco-predict-backend-space #namespace
spec:
  selector:
    app: eco-predict-backend #app-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32040 #port to be define
  type: NodePort
