name: API-PYTHON-BACKEND-DEV

on:
  # Triggers the workflow on push or pull request events for branches starting with "dev-"
  push:
    branches: [ "dev-*" ]

  # Allows manual execution of the workflow from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up Docker to build and push the image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-python-backend:dev-${{ github.sha }} .

      # Push the Docker image to Docker Hub (or another registry)
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/api-python-backend:dev-${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Set up kubectl to interact with the Kubernetes cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Use the kubeconfig from GitHub secrets
      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # Deploy to Kubernetes using kubectl
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/api-python-backend-deployment api-python-backend=${{ secrets.DOCKER_USERNAME }}/api-python-backend:dev-${{ github.sha }}
          kubectl rollout status deployment/api-python-backend-deployment
